### ISSUE TITLE
ValueError: not enough values to unpack(expected 2, got1)

### ISSUE THREAD

**Issue by zdk427** [HaploKit/Strainline#11]
@HaploKit

I have tried running the given example (reads.fa) file for haplotype calling, it works perfectly fine for me.

Currently trying to run my ONT obtained reads from GridIon Run to identify haplotypes. Every time, I am getting a specific error enlisted below in bold: 
......read overlaps filtering finished.
processing the 34 seed read...
processing the 34 seed read...
Traceback (most recent call last):
  File "/home/ngs/Downloads/Strainline-master/src/clustering.py", line 172, in <module>
    cluster_list = get_clusters(in_fa, outdir, int(topk), platform, int(threads), int(min_ovlp_len),
  File "/home/ngs/Downloads/Strainline-master/src/clustering.py", line 92, in get_clusters
    header, seq = id2fa[id].strip().split('\n')
**ValueError: not enough values to unpack (expected 2, got 1)**
(strainline) ngs@ngs-ThinkCentre-M93p:~/Desktop/trialstrainline/example$

Is there any modification that is to be done specifically for ONT reads in **Strainline.sh** file or do i need to modify my input file obtained from ONT run?

**Please find the attached snapshot for your reference:**

![image](https://user-images.githubusercontent.com/104396679/191329712-cda458d9-0e76-4e96-aa80-db897ae92dd1.png)

**Comment by HadrienRegue** [comment]
@zdk427 : Did you solve this issue?
I have the same error with my ONT data, and no problems with the testing dataset.
Thanks.

**Comment by LaraFuhrmann** [comment]
Hi, 
I am running into the same issue when executing Strainline on the example data following the instruction in the README, for both ONT and PacBio: 
`strainline.sh -i reads.fa -o out -p pb -k 20 -t 32`
`strainline.sh -i reads.fa -o out -p ont -t 32`

Did you manage to fix this issue?

**Comment by npdungca** [comment]
@zdk427: did you manage to solve this issue? How?

**Comment by linvei** [comment]
I ran the example data with ont datatype and same error happened. Anyone solved this ?
